### NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [54]:
import numpy as np #alias name

In [56]:
?np

In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array

In [3]:
print(a)

[1 2 3]


In [4]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [5]:
print(a.shape)            # Prints "(3,)"

(3,)


In [6]:
print(a[0], a[1], a[2])   # Prints "1 2 3"

1 2 3


In [7]:
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

[5 2 3]


In [8]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array

In [9]:
print(b.shape)                     # Prints "(2, 3)"\

(2, 3)


In [10]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

1 2 4


In [11]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [12]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1.]]


In [13]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [14]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0.]
 [0. 1.]]


In [15]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)

[[0.68285877 0.62054965]
 [0.29450464 0.42764089]]


### Array indexing

In [16]:


# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

In [19]:
b

array([[2, 3],
       [6, 7]])

In [20]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"


2


In [21]:
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

77


In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Datatypes

In [23]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"


int32


In [24]:

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"


float64


In [25]:

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64


### Array math


In [26]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [27]:
x

array([[1., 2.],
       [3., 4.]])

In [28]:
y

array([[5., 6.],
       [7., 8.]])

In [29]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [30]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [31]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [32]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [33]:
np.subtract(y,x)

array([[4., 4.],
       [4., 4.]])

In [34]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [35]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [36]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [37]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [38]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [39]:
np.sqrt(y)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [40]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [41]:
v.dot(w)

219

In [42]:
np.dot(v,w)

219

In [43]:
x.dot(v)

array([29, 67])

In [44]:
np.dot(x,v)

array([29, 67])

In [45]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [46]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [47]:
x = np.array([[1,2],[3,4]])

In [48]:
x

array([[1, 2],
       [3, 4]])

In [49]:
np.sum(x)

10

In [50]:
np.sum(x,axis = 0)

array([4, 6])

In [51]:
np.sum(x,axis =1)

array([3, 7])

In [52]:
x.T

array([[1, 3],
       [2, 4]])

In [53]:
x

array([[1, 2],
       [3, 4]])