### NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [1]:
import numpy as np #alias name

In [2]:
?np

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
l1 = [1,2,3,4,5]
b = np.array(l1)

In [7]:
type(l1)

list

In [8]:
type(b)

numpy.ndarray

In [9]:
a.shape  # show the shape of the array

(3,)

In [10]:
a[0]

1

In [11]:
a[1]

2

In [12]:
a[2]

3

In [13]:
a.size #number of elements in the array

3

In [14]:
a[0] = 5 # Change an element of the array
print(a) # Prints "[5, 2, 3]"

[5 2 3]


In [15]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array

In [16]:
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
print(b.shape)  # Prints "(2, 3)"\

(2, 3)


In [18]:
b.size

6

In [89]:
b

array([[77,  3],
       [ 6,  7]])

In [90]:
#indexing using both row and column
b[0,0]

77

In [91]:
b[1,1]

7

In [93]:
#create a 5*5 array

c = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])

In [94]:
c.shape

(5, 5)

In [95]:
c.size

25

In [96]:
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]


In [97]:
c[3,2]

13

In [98]:
m = np.array([[1,4,6,7,8],[2,6,7,8,9],[22,44,77,55,44],[12,14,16,18,20],[3,5,7,9,0]])


In [99]:
m

array([[ 1,  4,  6,  7,  8],
       [ 2,  6,  7,  8,  9],
       [22, 44, 77, 55, 44],
       [12, 14, 16, 18, 20],
       [ 3,  5,  7,  9,  0]])

In [100]:
m.shape

(5, 5)

In [101]:
m.size

25

In [102]:
m[3,3]

18

### Zeros , Ones(unit matrix) , Identity Matrix

In [103]:
a = np.zeros((3,3))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [104]:
b = np.ones((2,3))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1. 1.]
 [1. 1. 1.]]


In [112]:
c = np.full((2,2),5)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[5 5]
 [5 5]]


In [106]:
d = np.eye(5)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [131]:
e = np.random.random((3,3))  # Create an array filled with random values
print(e)

[[0.14102823 0.67940702 0.0395154 ]
 [0.00860909 0.01169704 0.03844481]
 [0.98407467 0.65061306 0.17326486]]


### Array indexing

In [132]:


# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


In [133]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

In [39]:
b

array([[2, 3],
       [6, 7]])

In [40]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"


2


In [41]:
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

77


### Arange function

In [134]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [136]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [143]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Datatypes

In [144]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"


int32


In [145]:

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"


float64


In [146]:

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64


In [154]:

x = np.array([1, 2], dtype=np.float32)   # Force a particular datatype
print(x.dtype)                         

float32


In [153]:

x = np.array([1.9999, 2.5],dtype = np.int32)   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"


int32


In [152]:
x

array([1, 2])

### Array math


In [155]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [156]:
x

array([[1., 2.],
       [3., 4.]])

In [157]:
y

array([[5., 6.],
       [7., 8.]])

In [158]:
x+y #element level matrix addition

array([[ 6.,  8.],
       [10., 12.]])

In [159]:
np.add(x,y) #element level matrix addition

array([[ 6.,  8.],
       [10., 12.]])

In [161]:
x-y #element level matrix subtraction

array([[-4., -4.],
       [-4., -4.]])

In [162]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [163]:
y-x

array([[4., 4.],
       [4., 4.]])

In [164]:
np.subtract(y,x)

array([[4., 4.],
       [4., 4.]])

In [165]:
x*y  ##element level matrix multiplication

array([[ 5., 12.],
       [21., 32.]])

In [166]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [167]:
x/y ##element level matrix division

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [168]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [169]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [170]:
np.divide(y,x)

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [171]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [172]:
np.sqrt(y)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [226]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8],[9,10]], dtype=np.float64)

In [174]:
np.add(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [175]:
np.subtract(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [177]:
np.multiply(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [178]:
np.divide(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [180]:
np.exp(x) #element level exponential 

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [185]:
np.log(x) #element level log

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [227]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [228]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [229]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

### Floor,Ceil,Round

In [234]:
x = np.array([[1.5,2.5],[3.1,4.9]], dtype=np.float64)

In [235]:
x

array([[1.5, 2.5],
       [3.1, 4.9]])

In [231]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [232]:
np.ceil(x)

array([[2., 3.],
       [4., 5.]])

In [233]:
np.round(x)

array([[2., 2.],
       [3., 5.]])

In [195]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
z = np.array([[9,10],[11,12]], dtype=np.float64)

In [196]:
x

array([[1., 2.],
       [3., 4.]])

In [197]:
y

array([[5., 6.],
       [7., 8.]])

In [198]:
z

array([[ 9., 10.],
       [11., 12.]])

In [199]:
x+y+z

array([[15., 18.],
       [21., 24.]])

In [200]:
x*y*z

array([[ 45., 120.],
       [231., 384.]])

In [201]:
np.add(x,y,z) #only first 2 paramters are considered

array([[ 6.,  8.],
       [10., 12.]])

In [202]:
np.multiply(x,y,z) #only first 2 paramters are considered

array([[ 5., 12.],
       [21., 32.]])

In [203]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [204]:
v

array([ 9, 10])

In [205]:
w

array([11, 12])

In [206]:
v.dot(w)

219

In [207]:
np.dot(v,w)

219

In [209]:
x.dot(v)

array([29, 67])

In [210]:
np.dot(x,v)

array([29, 67])

In [211]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [66]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [212]:
x = np.array([[1,2],[3,4]])

In [213]:
x

array([[1, 2],
       [3, 4]])

In [214]:
np.sum(x)

10

In [215]:
np.sum(x,axis = 0)

array([4, 6])

In [216]:
np.sum(x,axis =1)

array([3, 7])

In [217]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [218]:
np.sum(x)

45

In [219]:
np.sum(x,axis=0)

array([12, 15, 18])

In [220]:
np.sum(x,axis=1)

array([ 6, 15, 24])

In [221]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [222]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [224]:
x==x.T.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [225]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### linspace and arange

In [245]:
np.linspace(0, 100, num=5)  #5 eqidistant elements from 1 to 100 

array([  0.,  25.,  50.,  75., 100.])

In [246]:
np.linspace(100,0,5)

array([100.,  75.,  50.,  25.,   0.])

In [247]:
sample = np.arange(1,100,5)

In [248]:
sample.shape

(20,)

In [249]:
sample

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

### reshape and ravel

In [250]:
sample.reshape((4,5))

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [251]:
sample.reshape((5,4))

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [253]:
sample.reshape((5,5))  #size mismatch

ValueError: cannot reshape array of size 20 into shape (5,5)

In [254]:
sample.reshape((3,3))  #size mismatch

ValueError: cannot reshape array of size 20 into shape (3,3)

In [255]:
s1 = sample.reshape((4,5))

In [256]:
s1

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [258]:
s2 = np.ravel(s1) #flattern

In [259]:
s2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [260]:
s2.shape

(20,)

In [261]:
s2.size

20

In [262]:
s1.shape

(4, 5)

In [263]:
s2.size

20

In [264]:
#END