In [1]:
import numpy as np 

In [7]:
a = np.array([[3,7],[9,1],[10,2]])

In [8]:
a

array([[ 3,  7],
       [ 9,  1],
       [10,  2]])

In [9]:
np.sort(a) 

array([[ 3,  7],
       [ 1,  9],
       [ 2, 10]])

In [10]:
np.sort(a,axis=0)

array([[ 3,  1],
       [ 9,  2],
       [10,  7]])

The numpy.argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.

In [15]:
x = np.array([3, 1, 2,6]) 

In [16]:
np.argsort(x) 

array([1, 2, 0, 3], dtype=int64)

In [17]:
np.sort(x)

array([1, 2, 3, 6])

#### argmax and argmin

These two functions return the indices of maximum and minimum elements respectively along the given axis.

In [18]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

In [19]:
np.argmax(a) 

7

In [20]:
np.argmin(a)

5