In [1]:
import numpy as np 

In [2]:
a = np.array([[3,7],[12,1],[10,2]])

In [3]:
a

array([[ 3,  7],
       [12,  1],
       [10,  2]])

In [4]:
a.shape

(3, 2)

In [5]:
np.sort(a) #default axis = 1 

array([[ 3,  7],
       [ 1, 12],
       [ 2, 10]])

In [6]:
np.sort(a,axis=1)

array([[ 3,  7],
       [ 1, 12],
       [ 2, 10]])

In [7]:
np.sort(a,axis = None) 

array([ 1,  2,  3,  7, 10, 12])

In [8]:
np.sort(a,axis=0)

array([[ 3,  1],
       [10,  2],
       [12,  7]])

### Argsort
The numpy.argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.

In [9]:
x = np.array([3, 2, 1, 6]) 

In [10]:
np.argsort(x) #returns the index after sorting

array([2, 1, 0, 3], dtype=int64)

In [11]:
np.sort(x)

array([1, 2, 3, 6])

#### argmax and argmin

These two functions return the indices of maximum and minimum elements respectively along the given axis.

In [12]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

In [13]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [14]:
np.argmax(a) 

7

In [15]:
np.max(a)

90

In [16]:
np.argmax(a,axis=0)

array([1, 2, 0], dtype=int64)

In [17]:
np.max(a,axis=0)

array([80, 90, 70])

In [18]:
np.argmax(a,axis=1)

array([2, 0, 1], dtype=int64)

In [19]:
np.max(a,axis=1)

array([70, 80, 90])

In [20]:
np.argmin(a)

5

In [21]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [22]:
np.argmin(a,axis=0)

array([0, 1, 1], dtype=int64)

In [23]:
np.argmin(a,axis=1)

array([0, 2, 0], dtype=int64)

In [24]:
np.max(a)

90

In [25]:
np.max(a,axis=1)

array([70, 80, 90])

In [26]:
np.max(a,axis=0)

array([80, 90, 70])

In [27]:
np.min(a)

10

In [28]:
np.min(a,axis=1)

array([30, 10, 50])

In [29]:
np.min(a,axis=0)

array([30, 20, 10])

In [30]:
a = np.array([0,10,20,30,40,50,0,-20])

In [31]:
np.nonzero(a)  #The numpy.nonzero() function returns the indices of non-zero elements in the input array.

(array([1, 2, 3, 4, 5, 7], dtype=int64),)

In [32]:
np.where(a >= 30) #The where() function returns the indices of elements in an input array where the given condition is satisfied.

(array([3, 4, 5], dtype=int64),)

In [33]:
np.extract(a>=30,a) #The extract() function returns the elements satisfying any condition.

array([30, 40, 50])

In [34]:
condition = np.mod(a,3)==0

In [35]:
condition = a>=10

In [36]:
np.extract(condition,a)

array([10, 20, 30, 40, 50])

In [37]:
a = np.array([1.5,2.5,3.5,4.5])

In [38]:
np.floor(a)

array([1., 2., 3., 4.])

In [39]:
np.ceil(a)

array([2., 3., 4., 5.])

In [40]:
np.round(a)

array([2., 2., 4., 4.])

In [41]:
a = np.array([1.25,2.5,3.75,4.34,5.65])

In [42]:
a

array([1.25, 2.5 , 3.75, 4.34, 5.65])

In [43]:
np.round(a)

array([1., 2., 4., 4., 6.])

In [44]:
np.around(a,1) #Evenly round to the given number of decimals.

array([1.2, 2.5, 3.8, 4.3, 5.6])

### PTP function is used for calculating Range

The numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

In [45]:
a = np.array([[30,70,50],[1,4,3],[2,4,90]]) 

In [46]:
a

array([[30, 70, 50],
       [ 1,  4,  3],
       [ 2,  4, 90]])

In [47]:
np.ptp(a)

89

In [48]:
np.ptp(a,axis=1)

array([40,  3, 88])

In [49]:
np.ptp(a,axis=0)

array([29, 66, 87])

In [50]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

In [51]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [52]:
np.percentile(a,60)

57.99999999999999

In [53]:
np.percentile(a,50,axis=1)

array([40., 20., 60.])

In [54]:
np.percentile(a,50,axis=0)

array([50., 40., 60.])

In [55]:
a = np.array([1,5,7,4,9,0,7,8,10])

In [56]:
a

array([ 1,  5,  7,  4,  9,  0,  7,  8, 10])

In [57]:
np.sort(a)

array([ 0,  1,  4,  5,  7,  7,  8,  9, 10])

In [58]:
np.median(a)

7.0

In [59]:
np.sum(a)/len(a)

5.666666666666667

In [60]:
np.mean(a)

5.666666666666667

In [61]:
np.std(a)

3.265986323710904

In [62]:
np.var(a)

10.666666666666666

In [63]:
#End